import 'dart:ffi';

import 'package:flexj/database/entities/table.dart';
import 'package:floor/floor.dart';

@Entity(
  tableName: 'Data',
  foreignKeys: [
    ForeignKey(
      childColumns: ['id2'],
      parentColumns: ['id'],
      entity: User,
    )
  ],
)
@entity
class Data {
  @PrimaryKey(autoGenerate: true)
  final int? id;

  final DateTime giorno;

  final int? steps; // numero di passi

  final int? bpm; // frequenza cardiaca media

  final int? sleep; // ore di sonno

  final int? cal; // calorie giornaliere

  //final Bool obiettivo; // obiettivo raggiunto : SI/NO

  final int? peso; // peso user

  final int? altezza; // altezza user

  final int? bmi; //BMI user

  // final int? maxsteps;

  // final int? maxcal;

  @ColumnInfo(name: 'id')
  final int id2;

  //Default constructor
  Data(this.id, this.giorno, this.steps, this.bpm, this.altezza, this.bmi,
      this.cal, this.peso, this.sleep, this.id2);
} //table 2

// class table2 {
//   //id will be the primary key of the table. Moreover, it will be autogenerated.
//   //id is nullable since it is autogenerated.
//   @PrimaryKey(autoGenerate: true)
//   final int? id;

//   final DateTime giorno;

//   final int? steps; // numero di passi

//   final int? bpm; // frequenza cardiaca media

//   final int? sleep; // ore di sonno

//   final int? cal; // calorie giornaliere

//   final Bool obiettivo; // obiettivo raggiunto : SI/NO

//   final int? peso; // peso user

//   final int? altezza; // altezza user

//   final int? bmi; //BMI user

//   final int? maxsteps;

//   final int? maxcal;

//   //Default constructor
//   table2(
//       this.id,
//       this.giorno,
//       this.steps,
//       this.bpm,
//       this.altezza,
//       this.bmi,
//       this.cal,
//       this.maxcal,
//       this.maxsteps,
//       this.obiettivo,
//       this.peso,
//       this.sleep);
// }//table 2